### PR TITLE
Updated file structure

### PR DESCRIPTION
**Pull request by jamal-bell**

### CODE REVIEW

**Comment by jamal-bell** [comment]
please approve for merge

**Review by chriscyber — COMMENTED** [review]
This is to merge to main right? Do we have a preference between mongo ObjectId or uuid?

**Comment by jamal-bell** [comment]
It's only the base structure that we went through together. I would eyeball it for now.

**Review by haonanguan — APPROVED** [review]
looks good!

**Review by chriscyber — APPROVED** [review]

**Pull request merged**
